spring:
	profiles:
		active:
		- dev
---
spring:
	profiles: dev
	application:
		name: microservicecloud-config-zyc-dev
---
spring:
	profiles: test
	application:
		name: microservicecloud-config-zyc-test